language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install -r requirements/test.txt 
    - sudo apt-get install libtre5 libtre-dev
    - python setup.py build 
script: nosetests tests --with-cov
after_success:
    - coveralls
